### ISSUE TITLE
Shows .obsidian folder

### ISSUE THREAD

**Issue by dmonder** [polyipseity/obsidian-show-hidden-files#2]
After installing this tool, I am now able to see my hidden folders, but I also see the .obsidian folder, which I do not want to see. How do I selectively hide folders?

**Comment by polyipseity** [comment]
Added. If you now download and enable the plugin from the [latest release](https://github.com/polyipseity/obsidian-show-hidden-files/releases/tag/latest), you should see an new option called "Show configuration folder". Turn it off to hide `.obsidian`.

There is also an extra option called "Showing rules", which allows for advanced filtering.

I will make an release later.
