### ISSUE TITLE
not work on ios(ipad)

### ISSUE THREAD

**Issue by fzh890523** [polyipseity/obsidian-show-hidden-files#5]
ipados 17.2

the same config(the same whole repo) which works fine on windows  becomes not-work on ios. just not work, `.obsidian` dir and all other `.`-prefixed dirs/files are not shown.

**Comment by polyipseity** [comment]
Fixed in [`v2.3.2`](https://github.com/polyipseity/obsidian-show-hidden-files/releases/tag/2.3.2).
