### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by HighPriest** [polyipseity/obsidian-show-hidden-files#8]
I have just synchronised my desktop vault with android phone & the settings look identical between Desktop & Android devices.

But, no .hidden files or directories appear or are detectable by other plugins on Android.

I have just noticed, I am on 2.3.2 version of the plugin, maybe it was fixed with 2.3.3?

**Comment by polyipseity** [comment]
As far as I know, the latest plugin (v2.3.3) works on my iPhone and Android device as well. There are two things that you can try:

1. Update to v2.3.3.
2. If it still does not work, try resetting "Showing rules" by click this button: !["Showing rules" reset button](https://github.com/user-attachments/assets/86d0f26c-7a78-402a-83e8-85f12e5f841e)
